### ISSUE TITLE
CI build with disabled mod-multipath_component

### ISSUE THREAD

**Issue by genalt** [sid-project/sid#12]
There is missing mpath_valid.h

**Comment by prajnoha** [comment]
The mpath_valid.h is part of the change for multipath source code which exposes "multipath -c" functionality as library function - it checks whether given device is a multipath component or not, also looking at existing multipath configuration. This means that we don't necessarily need two or more devices with the same serial/WWID number to tell whether the device is a multipath component.

Once the patch for multipath is upstream, we can enable multipath_component module again.

**Comment by trgill** [comment]
@prajnoha should I enable this build on rawhide?

**Comment by prajnoha** [comment]
Yup and that mpath library should also be in F33 too. Though, recently, I've noticed there was one incompatible change in the mpath lib (8bb6f6fd35342ab070d1a8a8ac4f2dbd18b7c063) - this is surely in rawhide, not sure if F33 has that change too. Anyway, the rawhide surely has everything needed.
