### ISSUE TITLE
problems with how util_str_iterate_tokens()  deals with quotes

### ISSUE THREAD

**Issue by bmarzins** [sid-project/sid#121]
I can see two problems with how util_str_iterate_tokens() deals with quotes, using UTIL_STR_DEFAULT_QUOTES and UTIL_STR_DEFAULT_DELIMS.

1. Quotes aren't delimiters, so if the function was processing `can't or won't`, it would find 3 tokens: `can't`, `t or won`, and `t`.  Since the quote isn't a delimiter, the first token will keep reading right past it. For reference, if `can't or won't` was part of a bash command line, it would become the single argument `cant or wont`.

2. It checks for escape characters, but doesn't remove the escapes. So, there is no way to get a token like `"quoted string"`. You could either get `quoted string` or `\"quoted string\"`. You also can't get the token `can't or won't`. 

The way I would suggest to solve this would be to change how quotes are dealt with, in three ways.
1. There is no way to escape a quote character, except by placing it in a quoted token, delimited by a different quote character.
2. If there is no delimiter before the start of a quoted token, it is appended on to the previous token.
3. If there is no delimiter after a quoted token, the next token is appended on to it.

With these changes, you could get the token `"quoted string"` by passing in `'"quoted string"'` and `can't or won't` by passing in `can"'"t or won"'"t`. Also, processing `can't or won't` would get you one token, `cant or wont`, just like bash would.

I'm pretty sure this change makes sense, but since this would only get called with the default delims and quotes for an external worker, and there's currently no way to execute an external worker, I'm not exactly sure how the command arguments and environment variables will get passed. So, perhaps I'm missing something.

**Comment by bmarzins** [comment]
Never mind. I wasn't thinking.  You can obviously already get `"quoted string"` with `'"quoted string"'` and `can't or won't` with`"can't or won't"`, and that was what I was really worried about.  So I still think we should remove or fix checking for the `\` character, since IMHO that's broken. The real question is, do we need to be able to handle tokens the include both quote types? What we can't currently have is a token like `Goonies don't say "die"`. I'm not sure if this is important, but with my proposed change, you could get this with `"Goonies don't say"' "die"'`

**Comment by bmarzins** [comment]
Also the possibility for the same character ending up in two tokens is still bad, even if there is a way to avoid it, if you know that you need to.

**Comment by prajnoha** [comment]
> I can see two problems with how util_str_iterate_tokens() deals with quotes, using UTIL_STR_DEFAULT_QUOTES and UTIL_STR_DEFAULT_DELIMS.
> 
> 1. Quotes aren't delimiters, so if the function was processing `can't or won't`, it would find 3 tokens: `can't`, `t or won`, and `t`.  Since the quote isn't a delimiter, the first token will keep reading right past it. For reference, if `can't or won't` was part of a bash command line, it would become the single argument `cant or wont`.

Oh, nice! I've never noticed this kind of string concatenation is supported in shell :) So yes, sure, let's do it that way too.

> 2. It checks for escape characters, but doesn't remove the escapes.

Right, that's a bug, the escapes should be removed here.

> 
> The way I would suggest to solve this would be to change how quotes are dealt with, in three ways.
> 
> 1. There is no way to escape a quote character, except by placing it in a quoted token, delimited by a different quote character.

It would be fine to still keep the escapes if we could, so we have the same possibilities as if we used this in shell. But I don't mind that much if we don't and make things simpler and we just use a combination of different types of quotes for that. I was just trying to mimic the shell here...

> 2. If there is no delimiter before the start of a quoted token, it is appended on to the previous token.

Yup.

> 3. If there is no delimiter after a quoted token, the next token is appended on to it.

Yup.
