### ISSUE TITLE
SID isn't compiling with -Wall

### ISSUE THREAD

**Issue by bmarzins** [sid-project/sid#123]
SID should be compiling with `-Wall`, to catch errors, but it's not, at least for me. Looking at configure.ac, I can see `AM_INIT_AUTOMAKE([foreign -Wall -Werror -Wno-portability])` which I thought should set this, but to actually compile with `-Wall`, I had to manually specify in when running `./configure`. It's possible that this is just my issue, but it doesn't seem likely, since I actually hit an issue when I turned on `-Wall`:
[resource: ubridge: fix uninitalized use of cmd_reg in _init_command()](https://github.com/sid-project/sid/pull/122/commits/d34124c25b0dbc00c1b7012b0aae944aafa6358f)

I'm not sure why `AM_INIT_AUTOMAKE` isn't setting these parameters, but hopefully someone who hates autotools less than me will have a better grasp of what's going on here.

**Comment by prajnoha** [comment]
Oh, haven't noticed that, will check...

**Comment by prajnoha** [comment]
Hmm, mine seems to be inserting the `-Wall` there: https://gist.github.com/prajnoha/6092fe478614d77c2211daf55696dffe

What version of autotools you're using?

**Comment by prajnoha** [comment]
Ah, wait! I have `CFLAGS` env var set :) So yes, it's not adding the proper default flags there as defined in the `configure.ac` if I unset my `CFLAGS` env var.

**Comment by prajnoha** [comment]
(...hate autotools too!)

**Comment by prajnoha** [comment]
> AM_INIT_AUTOMAKE([foreign -Wall -Werror -Wno-portability])

Well, these are actually options for checking the source/package, not the compilation, see "-W category" in https://www.gnu.org/software/automake/manual/html_node/automake-Invocation.html.

Right now, I don't know how to add global project `CFLAGS` to existing system default `CFLAGS` (which is usually `-g -O2`) and still be able to override that with custom `CFLAGS` from environment. Right now, I'm just defining the `CFLAGS` in the environment or with `configure CFLAGS=...` if I need to override that.

**Comment by prajnoha** [comment]
I came across the `AM_CFLAGS` variable that we could define and add to each `Makefile.am` file for any extra flags we'd need to apply. Then we'd have `$(CC) $(AM_CFLAGS) $(CFLAGS)` called for the compilation. That means, `AM_CFLAGS` could be defaults, while `CFLAGS` could still override it.

But I'd rather stay with defaults (not defining the `AM_CFLAGS` -  it would also need to be defined per each Makefile) and just have the `CFLAGS` environment variable for us to add any extra compilation options (like the `-Wall`).
