### ISSUE TITLE
Confusion about _setup_channel()

### ISSUE THREAD

**Issue by bmarzins** [sid-project/sid#125]
I'm trying to figure out how `_setup_channel()` is supposed to work with `worker_channel_spec->wire.ext.pipe.fd_redir`. My assumption is that it is for external workers, so that they can redirect `stdin` and `stdout` to pipes to communicate with the proxy, before exec'ing a separate program. If that's really the use case, then I assume that the code under `WORKER_WIRE_PIPE_TO_WORKER` that redirects a file descriptor of the main SID process worker_proxy, instead of the worker, is simply a mistake. But I can't understand how this would be used for `WORKER_WIRE_SOCKET` type channels. It would redirect file descriptors on both the main SID process and the worker. Since this is a bidirectional socket, it wouldn't make sense for redirection from any of the stdio file descriptors. Maybe I'm overlooking a potential use case for this.

But if this really just is for remapping the stdio file descriptors in external worker processes,  I think it would make sense to pull this redirection out of the `_setup_channel()` function, and add it to the `_run_external_worker()`. For one thing, it would simplify `_setup_channel()`. For another, it would make it easy to verify that we don't do any logging that could go to the `stdout` file descriptor between when we do the redirect and when we exec the function.  Otherwise there's a chance the log message could get sent to the proxy, which would just mess things up.

**Comment by prajnoha** [comment]
> I'm trying to figure out how `_setup_channel()` is supposed to work with `worker_channel_spec->wire.ext.pipe.fd_redir`. My assumption is that it is for external workers, so that they can redirect `stdin` and `stdout` to pipes to communicate with the proxy, before exec'ing a separate program. 

...it's supposed to be both ways - either pipe from worker to proxy (the most common use case for redirecting output from an external command). But also supporting the other way round - redirecting an FD from proxy to a worker. This case, right now, only for completeness.

> But I can't understand how this would be used for `WORKER_WIRE_SOCKET` type channels. It would redirect file descriptors on both the main SID process and the worker. Since this is a bidirectional socket, it wouldn't make sense for redirection from any of the stdio file descriptors. Maybe I'm overlooking a potential use case for this.

Yeah, this bit is unfinished, I forgot to complete that one. As it is written now, it's handling only redirection in the worker to proxy path. But the goal was for both ways again, that'll need some completion (adding 2 fd redir spec something around `worker_wire_spec.socket.in` and `worker_wire.socket.out`, but it's not probably important right now so let's just keep it for now for the unidirection from proxy to worker. 

> 
> But if this really just is for remapping the stdio file descriptors in external worker processes, I think it would make sense to pull this redirection out of the `_setup_channel()` function, and add it to the `_run_external_worker()`.

Not just stdio, but any fd in general...

> For one thing, it would simplify `_setup_channel()`. For another, it would make it easy to verify that we don't do any logging that could go to the `stdout` file descriptor between when we do the redirect and when we exec the function. Otherwise there's a chance the log message could get sent to the proxy, which would just mess things up.

If it'll make things more correct and cleaner, sure, we can clean that up a bit.

I have a small program with which I was testing this (also one more patch attached for issues I've just noticed): https://gist.github.com/prajnoha/8b1686b813c25f8a8d25b2c4cea917a9

**Comment by prajnoha** [comment]
Note: right now, a `worker-control` instance inside `ubridge` is used for creating worker processes to handle the processing of a uevent through modules. But a module will create its own instance of `worker-control` to spawn external binaries and catch/redirect the output and/or input from/to the external or internal workers (IOW, it won't be the SID main process catching the output from external binaries, it's going to be the module itself doing that.)

**Comment by prajnoha** [comment]
So we ended up with a rule where `worker_channel_spec->wire.ext.pipe.fd_redir` always references the FD to redirect on worker side, never on proxy side.

As for `WORKER_WIRE_SOCKET`, we can redirect only either input or output on worker side to/out of the socket, but never both at the same time - this would require us to define one more `fd_redir`-like param, but this is not needed at the moment. If there's a use for this in the future, we can revisit this and add the extra param.
