### ISSUE TITLE
Likely Bptree bug with prefix lookups

### ISSUE THREAD

**Issue by bmarzins** [sid-project/sid#128]
I'm pretty sure I've spotted a bptree bug that can break _find() with LOOKUP_PREFIX, which could cause looking up a range of keys by prefix with the bptree_iter_* code to fail. But before I go about fixing it, I just want to make sure I'm not missing something here.

So, as far as I can see, the bptree code doesn't enforce that the keys in its internal nodes are actually present in the leaf nodes. If you have not done any deletions from the bptree, the key for the rightmost record in each leaf node will also exist in an internal node as the key for the pointer to the subtree for which it is the rightmost entry (except for the rightmost entry in the entire bptree, whose key is only in the leaf node). But if you delete the rightmost record from a leaf block, the code doesn't always remove its key from the internal nodes of the bptree. If you look in _delete_entry() for the case where the leaf block is still valid after the key is removed, the only function that is called is _remove_entry_from_node(), which never touches the tree outside that leaf node. After this, the key to the removed record would still be in an internal node somewhere (again, unless its the rightmost record in the entire bptree). I assume that you already know about this, since you reference count the keys. If the code guaranteed that when you removed an entry from the bptree, its key was removed from the internal nodes as well as the leaf node, then you wouldn't need to reference count the keys. Once an entry was removed, its key would always be safe to free. But having internal keys that don't exist in the leaf nodes could cause _find() with LOOKUP_PREFIX to fail.

Imagine we are looking for all entries with a key starting with Prefix_x.  These entries exist in two sibling leaf nodes. The first node (Leaf1) has Prefix_x:key_a as its rightmost member. The second node (Leaf2) has Prefix_x:key_b as its leftmost member. Since Prefix_x:key_a is the rightmost key in a leaf block, but not the rightmost member of its parent, its key will be in its parent's node (Node1). When looking for the first key whose prefix matches Prefix_x, the bptree _find() code will see the key in Node1, look in Leaf1, and find Prefix_x:key_a.

But if Prefix_x:key_a is deleted, the bptree code won't necessarily remove that key from Node1. After this deletion, when looking for the first key whose prefix matches Prefix_x, the code will still look in Leaf1, not Leaf2.  When it doesn't find any keys in the leaf that match Prefix_x, it will assume that there aren't any matching entries, because it looked in the leaf where they belonged and didn't find any.

Assuming that I'm not missing something here, I plan on updating the code to make sure that removing a key from a leaf node will cause it to get removed from the internal nodes as well. This should also let us drop bptree_key_t and just use a pointer to the key string, which will get freed when the key is remove from the leaf.

**Comment by prajnoha** [comment]
Yeah, that looks like a bug! Nice catch.

Though, maybe, in this exact case of LOOKUP_PREFIX with not finding a match in the expected leaf node, we could just simply follow the pointer at the end of current node which points to the next sibling node (node->pointers[bptree->order - 1]) and we could check whether we have a prefix match in the sibling (the first key there). If yes, we'll return that node/key instead.

If we could do that instead to fix the issue, that would be probably better? (Leaving a comment in the '_find' fn telling why we're doing this.)

We wouldn't need to do the copies of the keys and propagate them up the tree then. Also, keeping the ref-counted bkeys in would leave us space for future enhancements like returning keys without a need to copy them first and still be able to read them outside even if we fiddled with the bptree itself.

**Comment by bmarzins** [comment]
What do you think about 59c4f09016136af392249b70de5e4f3195511920? It leaves the ref-counted bkeys, but swaps the key in the internal notes to match the actual rightmost key in the leaf. This keeps us from storing keys with no records in the tree. While it does need to walk through the tree looking for matches, it's only when deleting the last key of a leaf, and it's not too expensive of an operation. If you'd rather change the _find() code instead, I can do that.

**Comment by prajnoha** [comment]
OK, the 59c4f09 looks like a good compromise so we can use that.

**Comment by prajnoha** [comment]
Commit b59913d23c837d62ae2e3d859f13a7079e5cdf9a fixes the issue (merged).
