### ISSUE TITLE
setup Jenkins CI for SID

### ISSUE THREAD

**Issue by trgill** [sid-project/sid#53]
@prajnoha if it is ok with you, I'd like to setup Jenkins to run on PRs.

**Comment by prajnoha** [comment]
Sure, we can give it a try! To be honest, I haven't used Jenkins yet, so I can't weigh much. But if we have a decent CI, that would be great.

So far, I've used only travis, but currently, it doesn't actually do much - just checks whether the code is compilable and some formatting checks. Actually, this was set up by Gennadii when he was here, not me, and I haven't added more checks since then, shame on me...

**Comment by prajnoha** [comment]
...I suppose you'll need some permissions here on github for this project to set the bindings, right? If so, let me know and I'll add the perms for you...

**Comment by trgill** [comment]
@prajnoha please add me as a member of the project:  https://github.com/orgs/sid-project/people

**Comment by prajnoha** [comment]
OK, done, you should receive an invitation....

**Comment by trgill** [comment]
The build/install is now running on Fedora 33.  Should I add Centos Stream?

**Comment by prajnoha** [comment]
Great, thanks! Maybe we could also add Fedora Rawhide as that's where "bleeding edge" changes go and if some dependency we use adds something new or there are some changes, we can test it right away. The Centos Stream - yeah, that's like rawhide, but for RHEL in a way, so if possible, we might as well test with that one.

**Comment by trgill** [comment]
Jenkins is updated to build Rawhide and Centos Stream for PRs now.

**Comment by prajnoha** [comment]
Thank you!

**Comment by trgill** [comment]
I think we should move towards having Jenkins just invoke a single script that we keep in git.  

@prajnoha if this sounds ok to you, I'll open a PR that will create a "ci" subdirectory that contains our CI scripts?

Jenkins is now running the following:

```
./autogen.sh

./configure --enable-mod-dm_mpath=false HAVE_CMOCKA=1

make

sudo make check

sudo make install

sudo systemctl start sid

/usr/lib/udev/usid active

sudo systemctl stop sid

sudo make uninstall
```

**Comment by prajnoha** [comment]
Sure, go ahead, sounds reasonable to have that directly in our repo...

**Comment by trgill** [comment]
Jenkins is failing right now with:

```
# make check
make  test_buffer test_hash test_notify test_kv_store test_bitmap test_usid
make[1]: Entering directory '/home/todd/workspace/sid/tests'
  CC       test_buffer.o
In file included from test_buffer.c:3:
/usr/include/cmocka.h:2180:8: error: unknown type name ‘jmp_buf’
 2180 | extern jmp_buf global_expect_assert_env;
      |        ^~~~~~~
make[1]: *** [Makefile:677: test_buffer.o] Error 1
make[1]: Leaving directory '/home/todd/workspace/sid/tests'
make: *** [Makefile:987: check-am] Error 2
```

I'm looking at why.

**Comment by trgill** [comment]
It looks like the reformat alphabetized the includes.  That creates problems for cmocka.  Will open a PR.

**Comment by prajnoha** [comment]
I forgot to check "make check", I should have put this through PR! My fault, sorry! This would be just one more rule in the `.clang-format` settings - PR #84

**Comment by trgill** [comment]
@prajnoha Thanks.

What version of clang-format are you using?  I'm using the packaged version with F32:

clang-format version 10.0.1 (Fedora 10.0.1-3.fc32)

I'm having problems with the .clang-format file.... For example:

```
# clang-format -i test_buffer.c
YAML:42:21: error: unknown key 'BeforeLambdaBody'
  BeforeLambdaBody: false
                    ^~~~~
```

**Comment by prajnoha** [comment]
I'm on rawhide (a VM, not that brave to run it on the actual host machine, I'm used to this from my LVM times :) )
❯ clang-format --version
clang-format version 11.1.0 (Fedora 11.1.0-0.4.rc2.fc34)

F33 has:
❯ clang-format --version
clang-format version 11.0.0 (Fedora 11.0.0-2.fc33)

I've created the `.clang-format` out of a template with `clang-format -style=XXX -dump-config` (I don't remember which XXX style it was initially which I modified, probably `llvm`...). So it may contain a few rules which are not usable for us anyway - the lambda surely is one of them (C doesn't have any lambdas, that one is specific to C++).

**Comment by trgill** [comment]
I'll update my VM to F33.  Thanks.

**Comment by prajnoha** [comment]
Or we can shoot down some of the rules which are not applicable anyway - like that lambda thing...

**Comment by prajnoha** [comment]
Don't have F32 at hand - is there anything else it errors out on besides the `BeforeLambdaBody` setting? I can remove these so we can still run with older clang-format.

**Comment by trgill** [comment]
I just started the upgrade, but I saw the following errors on F32:

```
YAML:145:9: error: unknown enumerated scalar
UseTab: AlignWithSpaces
        ^~~~~~~~~~~~~~~
Error reading /home/todd/workspace/sid/.clang-format: Invalid argument

YAML:93:20: error: unknown key 'IndentExternBlock'
IndentExternBlock: AfterExternBlock
                   ^~~~~~~~~~~~~~~~
Error reading /home/todd/workspace/sid/.clang-format: Invalid argument

```

**Comment by trgill** [comment]
@prajnoha

We've got some Jenkins nodes allocated to SID that have scratch disks.  Currently just 5 4GB block devices - but we can add more if needed.

Any suggestions for tests?  I was thinking I'd create some LVM devices and then check the contents of the database via usid.

I'm currently using cmocka - but it might be easier to parse output in Python.  Thoughts?

**Comment by prajnoha** [comment]
Right now, we don't have the LVM and other modules in place... except the mpath module, but that one also requires some more finishing once we have trigger-action code in - this is the part that I'm  working on right now so we can dive into modules more.

Currently, SID only collects very basic "holders/slaves" structure available from `/sys` that can be done without module-specific code. So for further tests, we need to wait a bit for the other parts to land so we can glue them together.

Sure, `cmocka` is good for unit tests where we bind against direct chunks of code, but for real end-user interface - the cmd line testing as a whole (the `sidctl output etc.), scripts seem to be more useful. I don't have any preference there - if you're used to Python, I'm perfectly fine with that, it's definitely much better than pure shell. The requirement would be to use something that is widely available, not exotic, which Python surely meets.

We will also need some way to present and remove devices for the system, so we can also test how SID behaves when devices are hotplugged and then disconnected or when being temporarily inaccessible. Can we do this directly or do we need to simulate?

Related to testing,  I was also thinking about using some coverage tool so we could see which parts still need care with regard to the unit tests (the `cmocka` ones). I expect the coverage to be very low for now - we have just a bunch of ad-hoc units tests. If we could see some charts/statistics, that would be great. I haven't used these tools much so far, I just know about `gcov` existence, so I'd need to do a bit of exploration here what are the possibilities and choose one. Do you know about anything good?

**Comment by prajnoha** [comment]
> We will also need some way to present and remove devices for the system, so we can also test how SID behaves when devices are hotplugged and then disconnected or when being temporarily inaccessible. Can we do this directly or do we need to simulate?

(...and for mpath, we'd need devices devices that have same serial number/WWN)
