### ISSUE TITLE
Implement build verification test (BVT)

### ISSUE THREAD

**Issue by genalt** [sid-project/sid#8]
We need some basic testing for the build verification (Integrated via Travis).

- [x] 1) It should check the source code is buildable w/o any issues
- [ ] 2) Check the binary could be running as a daemon
- [ ] 3) Check socket is listening

**Comment by trgill** [comment]
The Jenkins tests now implement steps 2 and 3.  I think this can be closed.

**Comment by prajnoha** [comment]
Indeed, closing...
