### ISSUE TITLE
Use cmocka XML output for Jenkins integration(?)

### ISSUE THREAD

**Issue by prajnoha** [sid-project/sid#83]
Recently, I've added this patch for the test results to be more fine-grained: c2e8b478a757db5fc3f21dfb14dc341761a3ab28

But I've noticed that `cmocka` also supports XML output for test results. Various articles on the web say that this is the format that is accepted by Jenkins. I've no idea what would be different for Jenkins then, maybe the results would pop up somewhere in Jenkins directly so we don't need to parse the logs? Probably worth a try...

@trgill What do you think? If it's not usable, feel free to close this.

**Comment by trgill** [comment]
@prajnoha I'm having some trouble getting Jenkins to publish the results, but I should be able to work through those issues.  It looks something like:

![image](https://user-images.githubusercontent.com/13203542/110042403-ba658c80-7d13-11eb-921b-94f7cbbbdd9e.png)

The usid_test is failing when compiled with the --coverage flag.  Not sure what is going on there - I'll figure it out.

**Comment by prajnoha** [comment]
Nice, such graph would be very valuable! Though, all red now :)  But that's the point to show us...
