### ISSUE TITLE
/usr/local/sbin/sidctl dump --format json hangs on Centos Stream

### ISSUE THREAD

**Issue by trgill** [sid-project/sid#90]
Looks like it is easy to reproduce on Jenkins.

I modified the Jenkins job so we don't hang test nodes.  It now only runs the command on F33.  When this problem is fixed - we should update the Jenkins script to run the command on all.

**Comment by bmarzins** [comment]
I think my "resource: Don't create a signal event for SIGCHLD" pull request may fix this.  I hit a hang in the SID daemon when a sid worker exits on F30 (which causes sidctl calls to hang as well). I couldn't hit it on F33, but I think it could still be a possible on newer releases.

**Comment by trgill** [comment]
Fixed by #92
