### ISSUE TITLE
problem with mocking system calls when combined with --coverage flags

### ISSUE THREAD

**Issue by trgill** [sid-project/sid#94]
When code coverage is enabled/run on Jenkins - test_usid exits with 255 due to this issue:

https://blog.microjoe.org/2017/unit-tests-c-cmocka-coverage-cmake.html#code-coverage-with-gcov-and-lcov

Currently code coverage is disabled for that test on Jenkins.  We should fix the problem or switch code coverage tools.

**Comment by prajnoha** [comment]
Aha! Well, that should be fixable as documented in that article. But thing is I don't see where the `open` is mocked. I see that we're mocking `buffer_get_data`, `sd_notify` and `getenv`. But I suspect it might be the `getenv` that coverage code might use - I'll try fixing that one...

**Comment by prajnoha** [comment]
The `test_usid` was removed with db226dc and replaced with a different test which doesn't have the issue reported here.
